/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  title: "xlkit",
  tagline: "宣言的なExcel生成ライブラリ",
  favicon: "img/favicon.ico",
  url: "https://yn1323.github.io",
  baseUrl: "/xlkit/",
  organizationName: "yn1323",
  projectName: "xlkit",
  onBrokenLinks: "throw",
  i18n: {
    defaultLocale: "ja",
    locales: ["ja", "en"],
    localeConfigs: {
      ja: {
        label: "日本語",
        direction: "ltr",
      },
      en: {
        label: "English",
        direction: "ltr",
      },
    },
    path: "i18n",
  },
  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.js",
          editUrl: "https://github.com/yn1323/xlkit/tree/main/website/",
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      },
    ],
  ],
  themeConfig: {
    navbar: {
      title: "xlkit",
      items: [
        {
          type: "docSidebar",
          sidebarId: "tutorialSidebar",
          position: "left",
          label: "Docs",
        },
        {
          type: "localeDropdown",
          position: "right",
          dropdownItemsBefore: [],
          dropdownItemsAfter: [],
        },
        {
          href: "https://github.com/yn1323/xlkit",
          label: "GitHub",
          position: "right",
        },
      ],
      hideOnScroll: false,
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            {
              label: "Getting Started",
              to: "/docs/intro",
            },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/yn1323/xlkit",
            },
            {
              label: "npm",
              href: "https://www.npmjs.com/package/xlkit",
            },
          ],
        },
      ],
      copyright: "Copyright © 2026 xlkit. Built with Docusaurus.",
    },
    prism: {
      theme: {
        plain: {
          color: "#393A34",
          backgroundColor: "#f6f8fa",
        },
        styles: [
          {
            types: ["comment", "prolog", "doctype", "cdata"],
            style: {
              color: "#999988",
              fontStyle: "italic",
            },
          },
          {
            types: ["namespace"],
            style: {
              opacity: 0.7,
            },
          },
          {
            types: ["string", "attr-value"],
            style: {
              color: "#e3116c",
            },
          },
          {
            types: ["punctuation", "operator"],
            style: {
              color: "#393A34",
            },
          },
          {
            types: [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted",
            ],
            style: {
              color: "#36acaa",
            },
          },
          {
            types: ["atrule", "keyword", "attr-name", "selector"],
            style: {
              color: "#00a4db",
            },
          },
          {
            types: ["function", "deleted", "tag"],
            style: {
              color: "#d73a49",
            },
          },
          {
            types: ["function-variable"],
            style: {
              color: "#6f42c1",
            },
          },
          {
            types: ["tag", "selector", "keyword"],
            style: {
              color: "#00009f",
            },
          },
        ],
      },
      darkTheme: {
        plain: {
          color: "#F8F8F2",
          backgroundColor: "#282A36",
        },
        styles: [
          {
            types: ["prolog", "constant", "builtin"],
            style: {
              color: "rgb(189, 147, 249)",
            },
          },
          {
            types: ["inserted", "function"],
            style: {
              color: "rgb(80, 250, 123)",
            },
          },
          {
            types: ["deleted"],
            style: {
              color: "rgb(255, 85, 85)",
            },
          },
          {
            types: ["changed"],
            style: {
              color: "rgb(255, 184, 108)",
            },
          },
          {
            types: ["punctuation", "symbol"],
            style: {
              color: "rgb(248, 248, 242)",
            },
          },
          {
            types: ["string", "char", "tag", "selector"],
            style: {
              color: "rgb(255, 121, 198)",
            },
          },
          {
            types: ["keyword", "variable"],
            style: {
              color: "rgb(189, 147, 249)",
              fontStyle: "italic",
            },
          },
          {
            types: ["comment"],
            style: {
              color: "rgb(98, 114, 164)",
            },
          },
          {
            types: ["attr-name"],
            style: {
              color: "rgb(241, 250, 140)",
            },
          },
        ],
      },
      additionalLanguages: [],
      magicComments: [
        {
          className: "theme-code-block-highlighted-line",
          line: "highlight-next-line",
          block: {
            start: "highlight-start",
            end: "highlight-end",
          },
        },
      ],
    },
    colorMode: {
      defaultMode: "light",
      disableSwitch: false,
      respectPrefersColorScheme: false,
    },
    docs: {
      versionPersistence: "localStorage",
      sidebar: {
        hideable: false,
        autoCollapseCategories: false,
      },
    },
    blog: {
      sidebar: {
        groupByYear: true,
      },
    },
    metadata: [],
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 3,
    },
  },
  baseUrlIssueBanner: true,
  future: {
    v4: {
      removeLegacyPostBuildHeadAttribute: false,
      useCssCascadeLayers: false,
    },
    experimental_faster: {
      swcJsLoader: false,
      swcJsMinimizer: false,
      swcHtmlMinimizer: false,
      lightningCssMinimizer: false,
      mdxCrossCompilerCache: false,
      rspackBundler: false,
      rspackPersistentCache: false,
      ssgWorkerThreads: false,
    },
    experimental_storage: {
      type: "localStorage",
      namespace: false,
    },
    experimental_router: "browser",
  },
  onBrokenAnchors: "warn",
  onDuplicateRoutes: "warn",
  staticDirectories: ["static"],
  customFields: {},
  plugins: [],
  themes: [],
  scripts: [],
  headTags: [],
  stylesheets: [],
  clientModules: [],
  titleDelimiter: "|",
  noIndex: false,
  markdown: {
    format: "mdx",
    mermaid: false,
    emoji: true,
    mdx1Compat: {
      comments: true,
      admonitions: true,
      headingIds: true,
    },
    anchors: {
      maintainCase: false,
    },
    hooks: {
      onBrokenMarkdownLinks: "warn",
      onBrokenMarkdownImages: "throw",
    },
  },
};
